/**It is important that this is present in every API.
 * @access For server side only.
 */
export const backendURL = { baseURL: process.env.API_URL };

export const INSTRUCTIONS_STEPS = [
  {
    id: 1,
    text: "Відкрий магазин додатків на своєму пристрої і знайдіть застосунок Крафтяр",
  },
  {
    id: 2,
    text: "Після знаходження додатка натисніть кнопку Встановити та дочекайтеся завершення процесу встановлення",
  },
  {
    id: 3,
    text: "Відкрийте додаток Крафтяр, зареєструйся і шукай фахівців або завдання, що тебе цікавлять",
  },
];

export const DUMMY_USERS = [
  {
    id: 1,
    name: "Матвій Коломієць",
    rating: 5.0,
    reviews: 5,
    profession: "Сантехнік",
    district: "Київ",
    avatar: "/static/boy.svg",
    lastOnline: "2год тому",
  },
  {
    id: 2,
    name: "Анастасія Коломієць",
    rating: 4.8,
    reviews: 74,
    profession: "Догляд за дитиною",
    district: "Тернопіль",
    avatar: "/static/girl.svg",
    lastOnline: "7год тому",
  },
  {
    id: 3,
    name: "Довгенькііііі значенняяяяяя",
    rating: 4.789,
    reviews: 99999,
    profession: "Догляд за тваринами",
    district: "Івано-Франківськ",
    avatar: "/static/boy.svg",
    lastOnline: "12годин тому",
  },
  {
    id: 4,
    name: "Короткі знач.",
    rating: 1.1,
    reviews: 1,
    profession: "Краса",
    district: "Львів",
    avatar: "/static/girl.svg",
    lastOnline: "Online",
  },
  {
    id: 5,
    name: "Матвій Коломієць",
    rating: 5.0,
    reviews: 5,
    profession: "Сантехнік",
    district: "Київ",
    avatar: "/static/boy.svg",
    lastOnline: "2год тому",
  },
  {
    id: 6,
    name: "Анастасія Коломієць",
    rating: 4.8,
    reviews: 74,
    profession: "Догляд за дитиною",
    district: "Тернопіль",
    avatar: "/static/girl.svg",
    lastOnline: "7год тому",
  },
  {
    id: 7,
    name: "Довгенькііііі значенняяяяяя",
    rating: 4.789,
    reviews: 99999,
    profession: "Догляд за тваринами",
    district: "Івано-Франківськ",
    avatar: "/static/boy.svg",
    lastOnline: "12годин тому",
  },
  {
    id: 8,
    name: "Короткі знач.",
    rating: 1.1,
    reviews: 1,
    profession: "Краса",
    district: "Львів",
    avatar: "/static/girl.svg",
    lastOnline: "Online",
  },
  {
    id: 9,
    name: "Матвій Коломієць",
    rating: 5.0,
    reviews: 5,
    profession: "Сантехнік",
    district: "Київ",
    avatar: "/static/boy.svg",
    lastOnline: "2год тому",
  },
  {
    id: 10,
    name: "Анастасія Коломієць",
    rating: 4.8,
    reviews: 74,
    profession: "Догляд за дитиною",
    district: "Тернопіль",
    avatar: "/static/girl.svg",
    lastOnline: "7год тому",
  },
  {
    id: 11,
    name: "Довгенькііііі значенняяяяяя",
    rating: 4.789,
    reviews: 99999,
    profession: "Догляд за тваринами",
    district: "Івано-Франківськ",
    avatar: "/static/boy.svg",
    lastOnline: "12годин тому",
  },
  {
    id: 12,
    name: "Короткі знач.",
    rating: 1.1,
    reviews: 1,
    profession: "Краса",
    district: "Львів",
    avatar: "/static/girl.svg",
    lastOnline: "Online",
  },
  {
    id: 13,
    name: "Матвій Коломієць",
    rating: 5.0,
    reviews: 5,
    profession: "Сантехнік",
    district: "Київ",
    avatar: "/static/boy.svg",
    lastOnline: "2год тому",
  },
  {
    id: 14,
    name: "Анастасія Коломієць",
    rating: 4.8,
    reviews: 74,
    profession: "Догляд за дитиною",
    district: "Тернопіль",
    avatar: "/static/girl.svg",
    lastOnline: "7год тому",
  },
  {
    id: 15,
    name: "Довгенькііііі значенняяяяяя",
    rating: 4.789,
    reviews: 99999,
    profession: "Догляд за тваринами",
    district: "Івано-Франківськ",
    avatar: "/static/boy.svg",
    lastOnline: "12годин тому",
  },
  {
    id: 16,
    name: "Короткі знач.",
    rating: 1.1,
    reviews: 1,
    profession: "Краса",
    district: "Львів",
    avatar: "/static/girl.svg",
    lastOnline: "Online",
  },
  {
    id: 17,
    name: "Матвій Коломієць",
    rating: 5.0,
    reviews: 5,
    profession: "Сантехнік",
    district: "Київ",
    avatar: "/static/boy.svg",
    lastOnline: "2год тому",
  },
  {
    id: 18,
    name: "Анастасія Коломієць",
    rating: 4.8,
    reviews: 74,
    profession: "Догляд за дитиною",
    district: "Тернопіль",
    avatar: "/static/girl.svg",
    lastOnline: "7год тому",
  },
  {
    id: 19,
    name: "Довгенькііііі значенняяяяяя",
    rating: 4.789,
    reviews: 99999,
    profession: "Догляд за тваринами",
    district: "Івано-Франківськ",
    avatar: "/static/boy.svg",
    lastOnline: "12годин тому",
  },
  {
    id: 20,
    name: "Короткі знач.",
    rating: 1.1,
    reviews: 1,
    profession: "Краса",
    district: "Львів",
    avatar: "/static/girl.svg",
    lastOnline: "Online",
  },
];
